- s3torchconnectorclient/Cargo.lock
Update Cargo.lock s3torchconnectorclient version
pip install ./s3torchconnectorclient --upgrade
--------
> Update Cargo.lock s3torchconnectorclient version

- .github/workflows/python-checks.yml
- s3torchconnector/docs/conf.py
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Update version number for release 1.1.0
Configuration updates needed for a new project release.
```pip install```
--------
> Update version for release 1.1.0

- CHANGELOG.md
We missed updating CHANGELOG.md for release v1.1.0. We should automate this flow. 
--------
> Update CHANGELOG.md for v1.1.0

- README.md
- README.md notes for how S3 Express is supported by Amazon S3 Connector for PyTorch.
- README changes previewed locally.
--------
> Add README.md notes for S3 Express One Zone support

- .github/workflows/notify-comment.yml
- .github/workflows/notify-issue-comment.yml
- .github/workflows/notify-issue.yml
- .github/workflows/notify-pr.yml
Individual notifier workflows for:
- PR creation
- New issues
- New comments on issues
Each notifier workflow has an associated slack webhook url secret added to the repository.
No code changes
Created a test PR, issue, and issue comments and verified that Slack messages are sent.
--------
> Add Slack Notifier workflow

- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
Use latest versions for:
mountpoint-s3-client = "0.6.2"
mountpoint-s3-crt = "0.6.0"
Consume latest Mountpoint release.
pip install -e "s3torchconnectorclient" --no-cache --upgrade
--------
> Update crates and Mountpoint dependencies

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
- Update version number and changelog.md for release 1.1.2
- Local build
--------
> Update version for release 1.1.2

- .github/workflows/generate_third_party_licenses.yml
Fixes failing workflow:
https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/7582543763/job/20653164703
Ran from custom branch: https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/7583075058
--------
> Fix mismatching dependencies versions

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Update version number for release 1.1.3
Checked diff for 1.1.2 update and verified the same files were changed.
--------
> Update version for release 1.1.3

- .github/workflows/ci-integration-main.yml
- .github/workflows/ci-integration-pr.yml
- .github/workflows/ci.yml
Run CI workflows on pull requests to feature branches, as we're working on merging lightning support to a feature branch, but tests aren't being ran on it.
--------
> Run tests on pull requests to feature branches

- .github/workflows/python-checks.yml
- .github/workflows/python-integration.yml
These do not exist on main, but are failing the workflow (https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/7899897992/job/21560272973?pr=143) on the feature branch, so we're just ignoring them until we release the feature, and let them run on the feature branch: https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/7899897645/job/21560271512
- Local and CI build
--------
> Ignore lightning tests

- .github/workflows/python-integration.yml
- s3torchconnector/pyproject.toml
- s3torchconnector/tst/e2e/models/__init__.py
- s3torchconnector/tst/e2e/models/lightning_transformer.py
- s3torchconnector/tst/e2e/models/net.py
- s3torchconnector/tst/e2e/test_e2e_s3_lightning_checkpoint.py
- s3torchconnector/tst/e2e/test_e2e_s3checkpoint.py
This PR adds E2E tests for Lightning checkpoints.
- https://github.com/awslabs/s3-connector-for-pytorch/pull/132
- Locally ran against personal S3 bucket
--------
> Add integration tests for Lightning support

- s3torchconnector/tst/e2e/test_e2e_s3_lightning_checkpoint.py
Add test for loading checkpoints through a trainer. 
- https://github.com/awslabs/s3-connector-for-pytorch/pull/143
- Local run against personal S3 bucket
--------
> Add Lightning checkpoint load test

- .github/workflows/python-checks.yml
- .github/workflows/python-integration.yml
- .github/workflows/wheels.yml
- s3torchbenchmarking/pyproject.toml
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/pyproject.toml
Add automated tests for building Python 3.12 in our CI, and for wheel building.
Add Python 3.12 to the list of supported Python versions in our PyPi page
No breaking changes, now supports Python 3.12
Passes new CI.
--------
> Add support to Python 3.12

- CHANGELOG.md
- s3torchconnector/src/s3torchconnector/_s3client/_mock_s3client.py
- s3torchconnector/src/s3torchconnector/_s3client/_s3client.py
- s3torchconnector/src/s3torchconnector/_user_agent.py
- s3torchconnector/src/s3torchconnector/_version.py
- s3torchconnector/tst/unit/test_s3_client.py
- s3torchconnector/tst/unit/test_user_agent.py
- s3torchconnectorclient/rust/src/mock_client.rs
Refactor User-Agent setup with an extensible configuration according to [RFC9110](https://www.rfc-editor.org/rfc/rfc9110#name-user-agent).
- Enhancements for previously added https://github.com/awslabs/s3-connector-for-pytorch/pull/65
- Unit tests
--------
> Refactor UserAgent setup for extensibility

- .github/pull_request_template.md
Adds a checkbox to the pull request template adding an additional question for if the changelog/readme is updated.
Used new template in this PR and verified the checkbox appears
--------
> Add checkbox to pull request template

- .github/workflows/python-checks.yml
- doc/DEVELOPMENT.md
- s3torchconnector/src/s3torchconnector/lightning/s3_lightning_checkpoint.py
'Fixes' `mypy` by adding `type: ignore` annotations to a few lines
`mypy s3torchconnector/src && mypy s3torchconnectorclient/python/src` passes
--------
> Add `type: ignore` annotations in various places to make mypy pass

- README.md
Add information about how S3MapDataset is able to support random access pattern. Explain that S3MapDataset has to build the list of all objects to support random access. This process could be resource demanding, so it would start only when user try to access the actual data. 
--------
> Provide information on how S3MapDataset works

- README.md
Updating README to include information how S3 Versioning can help with reduce checkpoints loss risks.
--------
> Add information about S3 Versioning to README

- .github/workflows/python-checks.yml
- s3torchconnectorclient/pyproject.toml
Update check and wheel workflow to support lightning module.
--------
> Fix test and wheel workflow

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Update project version to 1.20
--------
> Update version number to 1.2.0

- .github/workflows/python-checks.yml
- .github/workflows/python-integration.yml
- s3torchconnector/pyproject.toml
- s3torchconnector/tst/e2e/models/lightning_transformer.py
- s3torchconnector/tst/e2e/models/net.py
- s3torchconnectorclient/pyproject.toml
s3fs dependency should be optional, as it is used just by Lightning tests.
- Wheels workflow was tested by: https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/8263778332
--------
> Update Lightning dependencies and examples headers

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Update version number to 1.2.1
--------
> Update version number to 1.2.1

- s3torchconnectorclient/python/tst/integration/test_logging.py
When the hour is updating during the test run, there will be two log files.
--------
> Fix test for hour update

- s3torchconnectorclient/python/tst/integration/test_logging.py
Update test assertion to verify content of both files upon hourly update.
--------
> Update file content check

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Bump version number to 1.2.2.
--------
> Bump version number to 1.2.2

- doc/DEVELOPMENT.md
- s3torchconnector/src/s3torchconnector/_s3client/s3client_config.py
- s3torchconnectorclient/Cargo.lock
Updates for DEVELOPMENT.md, Cargo.lock and typos. 
--------
> Update DEVELOPMENT.md and fix typos

- doc/DEVELOPMENT.md
We do not expose the client, just its configuration. 
--------
> Fix example

- .github/workflows/wheels.yml
Updates our codebuild runner label to be the [new supported syntax](https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner-hosted.html)
Codebuild are removing the beta syntax imminently.
This PR ran the wheels workflow, and it passed.
--------
> Use new syntax for codebuild runners

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
- Use [mountpoint-s3-client-0.8.1](https://github.com/awslabs/mountpoint-s3/releases/tag/mountpoint-s3-client-0.8.1) and [mountpoint-s3-crt-0.7.0](https://github.com/awslabs/mountpoint-s3/releases/tag/mountpoint-s3-crt-0.7.0).
- Update version number to 1.2.3.
- Small nitpicks on CHANGELOG
- Local install + CI
--------
> Upgrade MP crates and version number to 1.2.3

- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/rust/src/mock_client.rs
- s3torchconnectorclient/rust/src/mountpoint_s3_client.rs
- s3torchconnectorclient/rust/src/mountpoint_s3_client_inner.rs
This picks up the latest CRT versions, including a bunch of performance and authentication fixes.
--------
> Update to latest Mountpoint client crates

- .github/workflows/python-checks.yml
- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Bump version number to 1.2.4
--------
> Update version for release 1.2.4

- s3torchconnector/src/s3torchconnector/s3writer.py
- s3torchconnector/tst/unit/test_s3writer.py
Add tell to writer to get current position of putobjectstream
- [ x] I have updated the CHANGELOG or README if appropriate
--------
> support tell for s3writer

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
- s3torchconnectorclient/rust/src/exception.rs
Update version for release 1.2.5. Includes the following changes:
* Enhanced error logging.
* Support tell for S3writer.
* Path-style addressing support.
* Update crates and Mountpoint dependencies.
NA
- [yes] I have updated the CHANGELOG or README if appropriate
NA
Ran all unit tests and integration tests
--------
> Update version for release 1.2.5

- s3torchconnector/src/s3torchconnector/_s3client/_s3client.py
- s3torchconnector/tst/e2e/test_e2e_s3checkpoint.py
- s3torchconnector/tst/e2e/test_mountpoint_client_parallel_access.py
Added integration tests for parallel checkpointing and parallel access of mountpoint client.
- [NA] I have updated the CHANGELOG or README if appropriate
--------
> Added fix for assertion error during parallel access of mountpoint client. Added integration tests for parallel access of mountpoint client.

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
ci: bump version numbers to 1.2.6
- #226
- #237
--------
> ci: bump version numbers to 1.2.6

- s3torchconnector/tst/e2e/dcp/test_e2e_s3_file_system.py
Integration tests for dcp
--------
> Integration tests for dcp

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Bump version to 1.3.0
--------
> Bump version to 1.3.0

- .github/workflows/python-checks.yml
- .github/workflows/python-integration.yml
- CHANGELOG.md
- README.md
- examples/dcp/stateful_example.py
- s3torchbenchmarking/conf/dcp.yaml
- s3torchbenchmarking/pyproject.toml
- s3torchbenchmarking/src/s3torchbenchmarking/dcp/README.md
- s3torchbenchmarking/src/s3torchbenchmarking/dcp/__init__.py
- s3torchbenchmarking/src/s3torchbenchmarking/dcp/benchmark.py
- s3torchbenchmarking/src/s3torchbenchmarking/dcp/constants.py
- s3torchbenchmarking/src/s3torchbenchmarking/dcp/models.py
- s3torchbenchmarking/src/s3torchbenchmarking/dcp/results.py
- s3torchconnector/pyproject.toml
- s3torchconnector/src/s3torchconnector/dcp/__init__.py
- s3torchconnector/src/s3torchconnector/dcp/s3_file_system.py
- s3torchconnector/src/s3torchconnector/s3iterable_dataset.py
- s3torchconnector/tst/e2e/conftest.py
- s3torchconnector/tst/e2e/dcp/__init__.py
- s3torchconnector/tst/e2e/dcp/test_e2e_s3_file_system.py
- s3torchconnector/tst/e2e/test_common.py
- s3torchconnector/tst/e2e/test_distributed_training.py
- s3torchconnector/tst/e2e/test_multiprocess_dataloading.py
- s3torchconnector/tst/unit/dcp/__init__.py
- s3torchconnector/tst/unit/dcp/test_s3_file_system.py
- s3torchconnector/tst/unit/test_s3iterable_dataset.py
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Add support of PyTorch Distributed Checkpoints and support of distributed training to S3IterableDataset
--------
> Distributed checkpoints/training

- .github/workflows/notify-comment.yml
- .github/workflows/notify-issue.yml
- .github/workflows/notify-pr.yml
- .github/workflows/notify-wheel-failure.yml
Replace INCOMING_WEBHOOK with incoming-webhook
--------
> Replace INCOMING_WEBHOOK with incoming-webhook

- s3torchconnector/src/s3torchconnector/dcp/s3_file_system.py
- s3torchconnector/tst/e2e/dcp/test_e2e_s3_file_system.py
Update user agent for DCP
--------
> Update user agent for DCP

- README.md
DCP sample in README.md has a few errors. We need to fix it.
--------
> Update DCP sample in README.md

- .github/workflows/rust-checks.yml
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/pyproject.toml
- s3torchconnectorclient/rust-toolchain.toml
Pin rust version to minimize changes from rust and deal with them in batches
--------
> Pin rust version to minimize changes from rust

- s3torchconnector/tst/e2e/dcp/test_e2e_s3_file_system.py
Temporary remove negative DCP e2e tests
--------
> Temporary remove negative dcp tests

- .github/workflows/python-checks.yml
- .github/workflows/python-integration.yml
- .github/workflows/wheels.yml
- CHANGELOG.md
- README.md
- s3torchbenchmarking/pyproject.toml
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/pyproject.toml
Add support for Python 3.13
--------
> Add support for Python 3.13

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Consume new version of mountpoint_s3_client and prepare changes for 1.4.0 release
--------
> Prepare changes for 1.4.0 release

- README.md
Update README prerequisites to show Python 3.8-3.12 support.
https://github.com/awslabs/s3-connector-for-pytorch/issues/336 
--------
> docs: update supported Python versions

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Update version for release 1.4.1. 
--------
> chore: update version for release 1.4.1

- .github/workflows/wheels.yml
- run_cibuildwheel_on_ec2.sh
- s3torchconnectorclient/pyproject.toml
Keep usage of manylinux_2014 for building wheels for wider suport of glibc.
--------
> Keep usage of manylinux_2014 for wider suport of glibc

- CHANGELOG.md
- s3torchconnector/pyproject.toml
- s3torchconnectorclient/Cargo.lock
- s3torchconnectorclient/Cargo.toml
- s3torchconnectorclient/pyproject.toml
Update version for release 1.4.3, and updated CHANGELOG to reflect our changes.
--------
> chore: update version for release 1.4.3

- .github/workflows/python-integration.yml
This PR: 
- Moves environment approval from matrix jobs to single gate job.
- Prevents 24+ deployment messages spamming PR conversation every PR sync.
Referenced https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/.github/workflows/e2e-test-untrusted.yaml.
--------
> ci: reduce deployment spam in PR conversation
