awslabs/s3-connector-for-pytorch

.github/workflows/python-checks.yml
.github/workflows/python-integration.yml

Workflows used old names for titles. Use the new package names instead.
--------

Use correct names for unit/integration test workflows

---

README.md

Update readme to use github.com URLs rather than relative URLs
On sites like PyPI we want to link people to github rather than keep them on-site.
This was the Readme we pushed to PyPI
--------

Update readme to use github.com URLs rather than relative URLs

---

conftest.py
s3torchconnector/pyproject.toml
s3torchconnectorclient/pyproject.toml

Previously we were having issues where our tests would take too long. Now they're set to time out after a specified period.
Tests pass.
--------

Add a 2-minute timeout to tests

---

s3torchconnector/src/s3torchconnector/_s3bucket_key.py
s3torchconnector/src/s3torchconnector/_s3dataset_common.py
s3torchconnector/src/s3torchconnector/s3iterable_dataset.py
s3torchconnector/src/s3torchconnector/s3map_dataset.py
s3torchconnector/tst/unit/test_s3dataset_common.py

Fix for https://github.com/awslabs/s3-connector-for-pytorch/issues/89
The goal of the changes was to minimize the retention time for S3 data loaded in memory. This was achieved by delaying the creation of `S3Readers` until right before reading the given object. Immediately after reading finishes, ownership of the `S3Reader` containing the loaded content is transferred to the calling client.
Integration and unit test were run.
--------

Avoid excessive memory consumption when utilizing s3map_dataset 

---

README.md

The checkpoint sample was updated to include backslash after the prefix/key to separate it from checkpoint name.
--------

Add backslash between prefix and checkpoint name

---

CHANGELOG.md
s3torchconnector/docs/conf.py
s3torchconnector/pyproject.toml
s3torchconnectorclient/Cargo.lock
s3torchconnectorclient/Cargo.toml
s3torchconnectorclient/pyproject.toml

Update version number and changelog.md for release 1.1.1
--------

Update version for release 1.1.1

---

examples/Getting started with the Amazon S3 Connector for PyTorch.ipynb

In https://github.com/awslabs/s3-connector-for-pytorch/issues/102, we found it wasn't obvious how to integrate `tar_file_expander` with `DataLoader`, and our example for tar file extraction skipped over it. 
This PR adds an explicit example for showing how to wrap an iterable such as one returned by `tar_file_expander` into a dataloader. 
No changes to the codebase.
https://github.com/awslabs/s3-connector-for-pytorch/issues/102
- Executed code for new changes and verified they behaved as expected.
- Viewed modified Jupyter notebook and saw that it was rendered correctly.
--------
By submitting this pull request, I confirm that my contribution is made under the terms of BSD 3-Clause License and I agree to the terms of the [LICENSE](https://github.com/awslabs/s3-connector-for-pytorch/blob/ma …

Be more explicit on how to use tar datasets with DataLoader in our example

---

s3torchconnector/docs/conf.py
s3torchconnector/src/s3torchconnector/__init__.py
s3torchconnector/tst/unit/test_version.py
s3torchconnectorclient/python/src/s3torchconnectorclient/__init__.py
s3torchconnectorclient/python/tst/unit/test_mountpoint_s3_client.py
s3torchconnectorclient/rust/src/lib.rs

Make version public for s3torchconnector and s3torchconnectorclient
Add `__version__` to the public interface for both s3torchconnector and s3torchconnectorclient, to be easier for us to verify which version a customer is using.
- Unit tests
--------

Add public version attributes

---

s3torchconnectorclient/python/src/s3torchconnectorclient/__init__.py
s3torchconnectorclient/python/src/s3torchconnectorclient/_logger_patch.py
s3torchconnectorclient/rust/src/lib.rs

Experimental function to enable CRT logs for debug purposes
We need a way to enhance our logging mechanism for debugging purposes. This PR adds a Python method that allows users to enable debug logs for our transitive client dependency, enhanced with a workaround for logging deadlocks known issue: https://docs.rs/pyo3-log/latest/pyo3_log/#interaction-with-python-gil
**This method is experimental and should not be used in production workloads.**
When needed, `_enable_debug_logging()` can be called in a test to have more verbose client side logs. It will print request metrics such as: request id, request type, start/end timestamp, bucket name, error code, etc.
- Locally ran an E2E test together with the following Python logging settings:
```
from s3torchconnectorclient import LOG_TRACE, …
```

Expose function to enable debug logging

---

.github/workflows/documentation.yml

Update documentation CI task to build local packages
Build local packages to fix import issue in docs generation task
We have previously removed hard-coded version number as part of https://github.com/awslabs/s3-connector-for-pytorch/pull/104. This broke the docs generation workflow:
```
Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
File "/home/runner/.local/lib/python3.10/site-packages/sphinx/config.py", line 358, in eval_config_file
exec(code, namespace)  # NoQA: S102
File "/home/runner/work/s3-connector-for-pytorch/s3-connector-for-pytorch/s3torchconnector/docs/conf.py", line 14, in <module>
from s3torchconnector import __version__
ModuleNotFoundError: No module named 's3torchconnector'
```
We are resolving this by …

Update documentation CI task to build local packages

---

.github/workflows/wheels.yml

Revert Github actions version upgraded with Dependabot
Downloading artifacts that were created from action/upload-artifact@v3 and below are not supported.
These should remain @v3 for now, ignore dependabot proposed upgrade.
- https://github.com/actions/download-artifact
- https://github.com/actions/upload-artifact/issues/478
https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/7584136329
--------

Fix download/upload artifact failures

---

s3torchconnectorclient/Cargo.lock
s3torchconnectorclient/Cargo.toml

Update the CRT from Mountpoint (and our other Rust dependencies).
- https://github.com/awslabs/mountpoint-s3/pull/713
The CRT update has two fixes we want:
- https://github.com/awslabs/aws-c-s3/pull/403
- https://github.com/awslabs/aws-c-auth/pull/225
`python -m pip install -e "./s3torchconnectorclient[test]" --upgrade` works, and integration tests pass locally.
--------

Update the Mountpoint CRT + other rust dependencies

---

.github/workflows/wheels.yml

Stop using a hardcoded artefact name, and use the same generation process ORT uses for it's own artefact name generation.
Third party license generation/wheel workflows were not working in forked repositories. This change fixes this.
Tested on a workflow in a private fork
--------

Fix wheel generation artefact name

---

s3torchconnector/src/s3torchconnector/_s3client/_s3client.py
s3torchconnector/src/s3torchconnector/s3iterable_dataset.py
s3torchconnector/src/s3torchconnector/s3map_dataset.py
s3torchconnector/tst/unit/test_checkpointing.py
s3torchconnector/tst/unit/test_s3_client.py
s3torchconnector/tst/unit/test_s3iterable_dataset.py
s3torchconnector/tst/unit/test_s3mapdataset.py

Adds logging at INFO level whenever a Dataset is constructed
Adds logging at DEBUG level whenever a HeadObject request is explicitly made from the s3torchconnector side. 
Added unit tests, ran a small example script and saw this in the output:
```
INFO s3torchconnector.s3map_dataset 2024-02-06 16:06:04,593 s3map_dataset.py:98 - Building S3MapDataset from_prefix
```
--------

Add additional logging for construction and HeadObject requests

---

.github/workflows/generate_third_party_licenses.yml
.github/workflows/wheels.yml

The wheel generation workflow was failing due to an issue with how the third party license name was being generated. Instead of running a regex to decide what it was called, export the environment variable across workflows so we know we always have the right name.
It was failing previously because `GITHUB_ENV` is not kept across workflows.
No breaking changes.
Wheel generation workflow now passes
--------

Fix wheel import of third party licenses

---

.github/workflows/rust-checks.yml
s3torchconnectorclient/Cargo.lock
s3torchconnectorclient/Cargo.toml

Previous PRs are blocked on Rust's cargo deny failing: https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/7867873103/job/21464194689?pr=138
These failures are unrelated to their content changes, but instead are due to a new security issue found in `libgit2-sys`. 
https://rustsec.org/advisories/RUSTSEC-2024-0013
This library is being pulled in by our `built` dependency for automatically including versioning information into the release. Mountpoint also used this library, pulling in an earlier version than we were wanting. This PR pulls in an updated Mountpoint version with a more recent dependency on `built`.
- `cargo deny check` passes
- `cargo test --no-default-features` passes
- `pytest` passes
--------
By submitting this pull request, I confirm that my …

Update mountpoint-s3-client to fix libgit2-sys security issue

---

.github/workflows/wheels.yml
s3torchconnectorclient/Cargo.lock
s3torchconnectorclient/pyproject.toml

Revert cc to 1.0.83 to fix wheels build workflow
We were seeing [this error](https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/7889988102/job/21531280591) after a Cargo update:
```
[  0%] Generating curve25519/curve25519_x25519base_alt.S.S
--- stderr
libunwind not found. Disabling unwind tests.
Copying platform assembly files from /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mountpoint-s3-crt-sys-0.5.3/crt/aws-lc/generated-src/linux-x86_64/crypto/ to /project/s3torchconnectorclient/target/release/build/mountpoint-s3-crt-sys-24feb138cf4a244b/out/build/aws-lc/build/crypto
gmake[1]: *** read jobs pipe: Resource temporarily unavailable.  Stop.
gmake[1]: *** Waiting for unfinished jobs....
gmake[2]: *** read jobs pipe: Resource temporarily unavailable.  Stop. …
```

Revert cc to 1.0.83 to fix wheels build workflow

---

s3torchconnector/tst/unit/test_s3dataset_common.py
s3torchconnector/tst/unit/test_s3reader.py
s3torchconnectorclient/python/tst/integration/test_mountpoint_s3_integration.py
s3torchconnectorclient/python/tst/unit/test_mountpoint_s3_client.py

Previously we had a mix and match of usage of raw `try`/`except` and `pytest.raises` without match blocks. As we decided we like `pytest.raises` with match, this commit makes us consistent across the repository
Tests still pass
--------

Use `pytest.raises` with match everywhere

---

run_cibuildwheel_on_ec2.sh

Build script is not allowing to pass custom s3 endpoint, because of initial check on the number of passed parameters.
Updated check to requires seven input parameters for the build script.
Run the build script to confirm that it is working
--------

Fix check on the number of passing parameters in build script

---

s3torchconnector/src/s3torchconnector/_s3_bucket_iterable.py
s3torchconnector/src/s3torchconnector/_s3bucket_key_data.py
s3torchconnector/src/s3torchconnector/_s3client/_s3client.py
s3torchconnector/src/s3torchconnector/_s3dataset_common.py
s3torchconnector/src/s3torchconnector/s3iterable_dataset.py
s3torchconnector/src/s3torchconnector/s3map_dataset.py
s3torchconnector/tst/unit/test_s3_client.py
s3torchconnector/tst/unit/test_s3iterable_dataset.py
s3torchconnector/tst/unit/test_s3mapdataset.py

- Ensure HeadObject is not explicitly called when seeking to the end of a file when dataset is created with from_prefix
- Rename `S3BucketKey` to `S3BucketKeyData`
- Change signature of `iter(S3BucketIterable)` to `Iterator[S3BucketData]` instead of `Iterator[S3Reader]`
https://github.com/awslabs/s3-connector-for-pytorch/issues/133
Extra tests added which verify that `head_object` is not called when seeking to the end of an S3Object when created using `from_prefix` for either dataset.
--------

Remove extra HeadObject call in from_prefix

---

.github/workflows/python-checks.yml
s3torchbenchmarking/pyproject.toml

Making it compatible with the installed torch version. Addresses build failures of the kind:
```
RuntimeError: operator torchvision::nms does not exist
```
Also, remove unnecessary s3torchconnector version constraint.
- [Addresses failing jobs like this one](https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/8018083826/job/21903264299)
- Created a virtualenv like the GH action would and was able to repro the issue locally. Tested that the fix works.
--------

Use cpu wheel for torchvision

---

.github/workflows/wheels.yml

- Automatically build ARM wheels in our CI with codebuild
- Also migrate x86 wheel builds to codebuild
- Total wheel build improved from 20-30 minutes to ~15 minutes
Passed workflow: https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/7991821909
Wheels artifact includes x86, arm, and source wheels.
--------

Add ARM runners to the CI

---

README.md
examples/lightning/async_checkpoint_writing.py
examples/lightning/checkpoint_manual_save.py
examples/lightning/checkpoint_reading.py
examples/lightning/checkpoint_writing.py

Adds four example files for using S3 connector for Pytorch with Pytorch Lightning:
- Reading from a checkpoint
- Writing to checkpoints automatically, including options to keep the most recent checkpoint only.
- Manually writing to a checkpoint
- Asynchronous checkpoint writing
Ran all files, and saw they wrote files, and read files from S3.
--------

Add examples for reading/writing checkpoints with lightning in various ways

---

CHANGELOG.md
s3torchconnector/src/s3torchconnector/lightning/s3_lightning_checkpoint.py
s3torchconnector/tst/e2e/test_e2e_s3_lightning_checkpoint.py

Use specific User-Agent for Lightning checkpoints with the following form: `s3torchconnector/{__version__} (lightning; {lightning.__version__}`, e.g., `s3torchconnector/1.1.4 (lightning; 2.2.0)`.
We have previously extended the User-Agent setup in https://github.com/awslabs/s3-connector-for-pytorch/pull/161.
- E2E tests
--------

Update User-Agent for Lightning checkpoints

---

s3torchbenchmarking/src/s3torchbenchmarking/models.py

There are discrepancy in where training data and model are located. When [train_batch](https://github.com/awslabs/s3-connector-for-pytorch/blob/main/s3torchbenchmarking/src/s3torchbenchmarking/models.py#L139) function of  `ViT` class is called, the input parameters such as `data` and `target` are moved to available device, when `model` is stayed on the default device. To prevent such discrepancy the `model` is moved to the same device as `data` and `target`.
That problem was reported in https://github.com/awslabs/s3-connector-for-pytorch/issues/166 issue.
Manually tested on instances with and without GPU (g5.8xlarge and c6a.4xlarge)
--------
By submitting this pull request, I confirm that my contribution is made under the terms of BSD 3-Clause License and I agree to the terms of the …

Move model's object to a correct device

---

.github/workflows/python-checks.yml

Pytest 8.1.1 starts to ignore `conftest.py` located in the root directory. That leads to error with loading `ci` profile for hypothesis. To prevent that issue, we will tell pytest to use current/root folder as working folder.
Tested changes locally
--------

Tell pytest to use current/root folder as working directory

---

.github/workflows/wheels.yml

Use [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) to allow running wheels workflow manually, when it is needed.
--------

Allow wheel workflow to run on demand

---

s3torchconnectorclient/pyproject.toml

Wheels build for feature/lightning-support is failing the compatibility tests with Lightning checkpoints for S3OZ, due to s3fs failing to find the bucket and trying to create a new one, action for which we do not grant permissions.
A subset of integration tests for S3OZ are failing when building our binaries.
We are running these tests as part of our [integration tests workflow](https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/8254183011/job/22577732929) on the feature branch, and they are not failing there, but only on the wheels build workflow. After a deep dive in the output, I noticed that for S3OZ the region was incorrectly set in the environment where the wheels are built.
- Stack trace:
```
_________________________ test_load_trained_checkpoint …
```

Fix wheels workflow for Lightning

---

CHANGELOG.md
doc/DEVELOPMENT.md
s3torchconnectorclient/Cargo.lock
s3torchconnectorclient/Cargo.toml
s3torchconnectorclient/python/tst/integration/test_logging.py
s3torchconnectorclient/python/tst/integration/test_mountpoint_s3_integration.py
s3torchconnectorclient/python/tst/unit/test_mountpoint_s3_client.py
s3torchconnectorclient/rust/src/logger_setup.rs

mountpoint-s3-client-0.8.0 contains changes incompatible with the logging setup.
Given the previous issues we had with this, we are separating these as follows: 
- Logging in the main Python component remains handled by Python logger.
- Logging in Rust components is handled by tracing_subscriber, set up through S3_TORCH_CONNECTOR_DEBUG_LOGS and S3_TORCH_CONNECTOR_LOGS_DIR_PATH environment variables. 
The [Python logger](https://docs.python.org/3/library/logging.html) handles logging messages from the Python-side of our implementation. For debug purposes, you can also enable the logs for our Rust components, which are off by default. These are handled by [tracing_subscriber](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/) and can be 
configured through the following …

Upgrade to mountpoint-s3-client-0.8.0 and update logging 

---

s3torchbenchmarking/README.md
s3torchbenchmarking/conf/dataloader/mountpoint.yaml
s3torchbenchmarking/src/s3torchbenchmarking/benchmark.py

Adds support for running benchmarks against mountpoints-backed datasets. The feature relies on the `mount-s3` binary being installed and relies on the `FSSpecFileLister` and `FSSpecFileOpener` APIs exposed by torchdata to interact with the filesystem. A reference configuration `dataloader/mountpoint.yaml` has already been created that can be used in experiments. 
Note: This feature mounts all the objects under an s3 prefix at a temporary path on the filesystem, and also manages the clean up of the same via a signal handler that is invoked when the process terminates.
Locally tested a sample scenario by running:
```
AWS_PROFILE=<PROFILE-NAME> ./venv/bin/s3torch-benchmark -cd conf -m -cn dataloading dataset.prefix_uri=<S3-PREFIX> dataloader=mountpoint dataset.region=<AWS-REGION>
```
``` …
```

Support benchmarking mountpoint-backed datasets

---

s3torchbenchmarking/README.md
s3torchbenchmarking/conf/checkpointing.yaml
s3torchbenchmarking/conf/dataloading.yaml
s3torchbenchmarking/conf/hydra/callbacks/collate_results.yaml
s3torchbenchmarking/conf/sharding.yaml
s3torchbenchmarking/src/s3torchbenchmarking/__init__.py
s3torchbenchmarking/src/s3torchbenchmarking/benchmark.py
s3torchbenchmarking/src/s3torchbenchmarking/benchmark_utils.py
s3torchbenchmarking/src/s3torchbenchmarking/hydra_callbacks.py
s3torchbenchmarking/src/s3torchbenchmarking/models.py

This change will make the benchmark results machine parseable and allow for future extensions like plotting, storage and regression testing.
Results of individual jobs are written out to dedicated `result.json` files. On Multirun end, all results are collated into a `collated_results.json`.
Other minor changes include:
- Introduce a bespoke Distribution type to accumulate scalar values and provide summarized stats on the distribution.
- Use the Distribution type in resource monitor and for checkpoint results.
-  Move resource monitoring logic into abstract `model.train` method.
[x] I have updated the CHANGELOG or README if appropriate
- https://github.com/awslabs/s3-connector-for-pytorch/issues/175
````
$ AWS_PROFILE=s3-open-source ./venv/bin/s3torch-benchmark -cd s3torchbenchmarking/conf …
```

Collate multirun results into a single json file

---

CHANGELOG.md
s3torchbenchmarking/src/s3torchbenchmarking/benchmark_utils.py
s3torchconnector/src/s3torchconnector/__init__.py
s3torchconnector/src/s3torchconnector/_s3client/__init__.py
s3torchconnector/src/s3torchconnector/_s3client/_mock_s3client.py
s3torchconnector/src/s3torchconnector/_s3client/_s3client.py
s3torchconnector/src/s3torchconnector/_s3client/s3client_config.py
s3torchconnector/src/s3torchconnector/lightning/s3_lightning_checkpoint.py
s3torchconnector/src/s3torchconnector/s3checkpoint.py
s3torchconnector/src/s3torchconnector/s3iterable_dataset.py
s3torchconnector/src/s3torchconnector/s3map_dataset.py
s3torchconnector/src/s3torchconnector/s3reader.py
s3torchconnector/tst/unit/test_s3_client.py
s3torchconnector/tst/unit/test_s3_client_config.py

We expose the following configuration flags with performance impact: `throughput_target_gbps` and `part_size`.
- `throughput_target_gbps(float)`: Throughput target in Gigabits per second (Gbps) that we are trying to reach.
10.0 Gbps by default (may change in future).
- `part_size(int)`: Size, in bytes, of parts that files will be downloaded or uploaded in.
Note: for saving checkpoints, the inner client will adjust the part size to meet the service limits.
(max number of parts per upload is 10,000, minimum upload part size is 5 MiB).
Part size must have values between 5MiB and 5GiB.
8MB by default (may change in future).
- Unit tests
--------
By submitting this pull request, I confirm that my contribution is made under the terms of BSD 3-Clause License and I agree to the terms of the …

Expose S3ClientConfig

---

CHANGELOG.md
doc/DEVELOPMENT.md
s3torchconnector/src/s3torchconnector/_s3client/_mock_s3client.py
s3torchconnector/src/s3torchconnector/_s3client/_s3client.py
s3torchconnector/src/s3torchconnector/_s3client/s3client_config.py
s3torchconnector/tst/e2e/test_e2e_s3datasets.py
s3torchconnector/tst/unit/test_s3_client.py
s3torchconnectorclient/python/src/s3torchconnectorclient/_mountpoint_s3_client.pyi
s3torchconnectorclient/python/tst/unit/test_mountpoint_s3_client.py
s3torchconnectorclient/rust/src/mock_client.rs
s3torchconnectorclient/rust/src/mountpoint_s3_client.rs

Update S3ClientConfig to pass in the configuration for allowing unsigned requests.
We no longer require credentials for accessing public data / data accessible through other mechanisms when using an unsigned client.
- Tested with the public examples bucket
- Added integration test for that
--------

Allow usage of unsigned S3 client

---

CHANGELOG.md
s3torchconnector/src/s3torchconnector/lightning/s3_lightning_checkpoint.py
s3torchconnector/tst/unit/lightning/test_s3_lightning_checkpoint.py

Added support for passing a custom endpoint to S3LightningCheckpoint. An endpoint optional argument is added to S3LightningCheckpoint constructor. 
Added a unit test case for lightning module. Tested with a customer S3 storage system.
--------

Added support for passing a custom endpoint to S3LightningCheckpoint

---

.github/workflows/ci-integration-main.yml
.github/workflows/python-checks.yml
.github/workflows/python-integration.yml
.github/workflows/rust-checks.yml
.github/workflows/wheels.yml
s3torchconnector/tst/e2e/test_e2e_s3_lightning_checkpoint.py

This is pretty simple, mostly just adding macos-13 (x86) and macos-14 (arm64) runners to the matrix. We also need to explicitly disable MPS for PyTorch to run correctly on the GHA runners which don't have access to that hardware.
--------
dnanuti@: Build on macos runners had occasionally a flaky behaviour, as `actions/setup-python` requires `/Users/runner/hostedtoolcache` to exist to work properly with macosx due to [fixed shared library path](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#macos).
Additionally, `pipx` was not always properly configured, depending on the runner image, encountered [this](https://github.com/actions/runner-images/issues/9607) on macos-14 arm64 runners too ([example run](https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/ …

Build macOS wheels and integration tests

---

s3torchconnectorclient/pyproject.toml

Centos 7 reached its End Of Life which lead to deprecation of official mirrors. cibuildwheels made changes to re-targed `yum` to vault with frozen packages, but it was lacking packages for aarch64 platform. Removing unnecessary packages helped to resolve that problem.
Run wheels build workflow
--------

Conditionally modify YUM repositories for aarch64

---

s3torchconnector/src/s3torchconnector/_s3client/_mock_s3client.py
s3torchconnector/src/s3torchconnector/_s3client/_s3client.py
s3torchconnector/src/s3torchconnector/_s3client/s3client_config.py
s3torchconnector/tst/unit/test_s3_client.py
s3torchconnector/tst/unit/test_s3_client_config.py
s3torchconnectorclient/python/src/s3torchconnectorclient/_mountpoint_s3_client.pyi
s3torchconnectorclient/python/tst/integration/test_mountpoint_s3_integration.py
s3torchconnectorclient/python/tst/unit/test_mountpoint_s3_client.py
s3torchconnectorclient/rust/src/mock_client.rs
s3torchconnectorclient/rust/src/mountpoint_s3_client.rs

This PR extends support to other S3 object storage like MinIO which has path-style addressing to access bucket/object.
An example is like
```py
from s3torchconnector import S3ClientConfig, S3MapDataset, S3IterableDataset
DATASET_URI="s3://<BUCKET>/<PREFIX>"
REGION = "us-east-1"
s3client_config = S3ClientConfig(force_path_style=True)
iterable_dataset = S3IterableDataset.from_prefix(DATASET_URI, region=REGION, s3client_config=s3client_config)
for item in iterable_dataset:
print(item.key)
map_dataset = S3MapDataset.from_prefix(DATASET_URI, region=REGION, s3client_config=s3client_config)
item = map_dataset[0]
bucket = item.bucket
key = item.key
content = item.read()
len(content)
```
And
```py
from s3torchconnector import S3Checkpoint, S3ClientConfig
import torchvision
import torch …
```

Add path-style addressing support

---

.github/workflows/rust-checks.yml
s3torchconnectorclient/deny.toml

EmbarkStudios/cargo-deny-action from 1 to 2 and Add version = 2 in deny.toml
Dependabot suggested to update the version of EmbarkStudios/cargo-deny-action from 1 to 2 , however integration tests where failing due to some deprecated keys in deny.toml. Added mitigation for the same.
NA
- [NA] I have updated the CHANGELOG or README if appropriate
NA
Ran unit and integration tests locally.
--------

EmbarkStudios/cargo-deny-action from 1 to 2 and Add version = 2 in deny.toml

---

.github/workflows/generate_third_party_licenses.yml
.github/workflows/wheels.yml

Migrated actions/download-artifact and actions/upload-artifact from v3 to v4. 
1. In v3, artifacts are mutable so it's possible to write workflow scenarios where multiple jobs upload to the same artifact. In v4, artifacts are immutable (unless deleted). So each of the uploaded artifacts must have a different name. Added mitigation for the same in this PR.
2. Added a new job in wheels.yml to merge all the wheels generated by the jobs.
https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md
- [NA] I have updated the CHANGELOG or README if appropriate
https://github.com/awslabs/s3-connector-for-pytorch/pull/209
Ran all unit and integration tests. Also generated wheels and checked https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/10923188484.
--------
By …

Migrated actions/download-artifact and actions/upload-artifact from v3 to v4. 

---

.github/workflows/python-checks.yml
.github/workflows/rust-checks.yml

Bump version of `actions/cache` from `@v3` to `@v4`, as recommended by warnings in CI runs
(https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/).

ci: update version of Cache action

---

s3torchbenchmarking/pyproject.toml
s3torchconnector/pyproject.toml

Restrain PyTorch version to below 2.5, since the latter creates some problem in our CI and wheels building.
See also: https://github.com/pytorch/pytorch/issues/138333
--------

fix: restrain PyTorch version to below 2.5

---

CHANGELOG.md
s3torchconnector/pyproject.toml
s3torchconnectorclient/Cargo.lock
s3torchconnectorclient/Cargo.toml
s3torchconnectorclient/pyproject.toml

Bump s3-connector-for-pytorch versions to v1.2.7.
--------

Bump s3-connector-for-pytorch versions to v1.2.7

---

.github/workflows/python-integration.yml

v3 runs on a deprecated Node.js version, and GitHub warns us to move on a new version (v4).
--------

ci: bump "actions/cache/*" version from v3 to v4

---

.github/workflows/wheels.yml

macOS wheel builds were failing due to an expiration timeout of the IAM role used for running integration tests. The builds were exceeding the one-hour limit. This change extends the timeout from one hour to two hours, allowing sufficient time for the builds to complete successfully.
Successful wheel build run https://github.com/awslabs/s3-connector-for-pytorch/actions/runs/11919193637/job/33218510050
--------

Extend aws role timeout

---

s3torchbenchmarking/src/s3torchbenchmarking/dcp/README.md
s3torchbenchmarking/src/s3torchbenchmarking/dcp/benchmark.py

Write `model.to(device=torch.device("cpu")` for gloo-based benchmarks instead of `model.to(device_id)`. Also, update DCP benchmarks README.md and add one extra caveat and its solution.
--------

fix(dcp): address bug in DCP + CPU benchmarks (gloo)

---

s3torchconnectorclient/pyproject.toml

As per https://cibuildwheel.pypa.io/en/stable/faq/#macos-library-dependencies-do-not-satisfy-target-macos, enforce `s3torchconnectorclient` module to build against macOS 10.12.
--------

ci: fix cibuildwheel for macOS

---

s3torchbenchmarking/pyproject.toml
s3torchconnector/pyproject.toml

Update dependency on torch to exclude 2.5.0 version that contains issue https://github.com/pytorch/pytorch/issues/138333
Limit torchdata version by 0.9.0 until we remove dependency on deprecated DataPipes, that were removed from 0.10.0
--------

Update torch version and bind torchdata to last version with DataPipes

---

.gitignore
s3torchbenchmarking/benchmark_results_aggregator.ipynb

Add a Jupyter Notebook to fetch and transform benchmark results into Pandas `DataFrame` and CSV file.
--------

feat(benchmarks): add Jupyter Notebook for results exploitation

---

CHANGELOG.md
s3torchconnector/src/s3torchconnector/dcp/s3_file_system.py
s3torchconnector/tst/e2e/dcp/test_e2e_s3_file_system.py
s3torchconnector/tst/unit/dcp/test_s3_file_system.py

If path contains special characters COPY request will fail. We need to escape special characters for COPY request.
https://github.com/awslabs/s3-connector-for-pytorch/issues/295
Update integration tests
--------

Escape special characters in path name for COPY request

---

s3torchbenchmarking/src/s3torchbenchmarking/datagen.py

Remove obsolete parameter `identifier`, as `consumer` method is not expected it anymore.
#301
Run s3torch-datagen
--------

Remove obsolete parameter

---

CHANGELOG.md
s3torchconnectorclient/Cargo.lock
s3torchconnectorclient/Cargo.toml
s3torchconnectorclient/rust/src/logger_setup.rs
s3torchconnectorclient/rust/src/mountpoint_s3_client.rs

Remove dependency on mountpoint-s3-crt by consuming new version (0.13.0) of mountpoint_s3_client
--------

Remove dependency on mountpoint-s3-crt and update MP

---

s3torchconnector/pyproject.toml
s3torchconnector/src/s3torchconnector/_s3client/_s3client.py
s3torchconnector/tst/e2e/test_mountpoint_client_parallel_access.py
s3torchconnectorclient/Cargo.lock
s3torchconnectorclient/Cargo.toml
s3torchconnectorclient/python/src/s3torchconnectorclient/_mountpoint_s3_client.pyi
s3torchconnectorclient/rust/src/lib.rs
s3torchconnectorclient/rust/src/mountpoint_s3_client.rs

Previously, since the underlying CRT client has multiple background threads, there are couple hacks have done to workaround the fork issue. **Notes: overall, fork with multi-threading is not encouraged and not well supported.**
1. check the PID to make sure every process creates its own s3 client
2. If the client was not created by the current process, leave the client in memory to avoid the clean up steps try to invoke background threads already gone.
Well, it works **mostly**.
CRT has some global state related to threads (There may be more than what I listed, I just listed what I have found so far)
1. https://github.com/awslabs/aws-c-common/pull/1181 for more details
2. https://github.com/awslabs/aws-c-common/blob/main/source/thread_shared.c#L16, there is a global mutex a background …

New work around for fork with multithread from CRT

---

CHANGELOG.md
s3torchconnectorclient/Cargo.lock
s3torchconnectorclient/Cargo.toml

Consume mountpoint-s3-client changes for race condition on GET request path, that may lead to an empty response.
Race condition on get_object path https://github.com/awslabs/mountpoint-s3/issues/1331
---
PIL UnidentifiedImageError training with higher 'num_workers' #293
--------

Consume mountpoint-s3-client v0.13.2

---

s3torchconnector/pyproject.toml
s3torchconnector/src/s3torchconnector/s3writer.py
s3torchconnector/tst/unit/test_s3writer.py

Address PyTorch 2.7.0 compatibility issues:
1. Add importlib_metadata dependency for Python 3.9
- Required by PyTorch 2.7.0 for e2e tests on Python 3.9
2. Improve S3Writer thread safety
- Add lock to prevent multiple/concurrent stream closures
- Add unit tests to verify thread-safe behavior
No breaking changes introduced.
- Added unit tests verifying thread-safe close() behavior:
- Multiple sequential close() calls
- Concurrent close() calls from multiple threads
- Verified e2e tests pass on Python 3.9 with PyTorch 2.7.0
--------

Support PyTorch 2.7.0

---

.github/workflows/python-integration.yml
s3torchconnector/tst/e2e/dcp/test_e2e_s3_file_system.py

Two issues were addressed in this PR:
1. DCP e2e tests were hanging in Github Actions
2. Distributed integration tests were intermittently returning Bad Request errors
DCP issue fix:
- Isolated process group initialization with explicit TCP arguments
- Added barrier synchronization point to ensure all processes complete before cleanup occurs
Using sequential runs:
- Removed parallel execution (-n auto) for both multi-process tests
DCP Issue:
In [`test_e2e_s3_file_system.py`](https://github.com/awslabs/s3-connector-for-pytorch/blob/main/s3torchconnector/tst/e2e/dcp/test_e2e_s3_file_system.py), `multi_process_dcp_save_load()` spawns multiple processes to execute `run()`. Environment-based process group initialization could lead to shared state and port conflicts, and a race condition occurs …

fix: resolve DCP test hanging and distributed test errors

---

s3torchconnectorclient/Cargo.lock
s3torchconnectorclient/Cargo.toml
s3torchconnectorclient/rust/src/get_object_stream.rs
s3torchconnectorclient/rust/src/mountpoint_s3_client_inner.rs

Update to mountpoint-s3-client v0.14.1 to address CRT timeout issues and adapt to API changes:
- Include aws-c-s3 first byte timeout fix (awslabs/aws-c-s3/pull/461)
- Update get_object functions to use new GetBodyPart type (awslabs/mountpoint-s3/pull/1348)
This addresses AWS_ERROR_HTTP_RESPONSE_FIRST_BYTE_TIMEOUT CRT error.
- CRT timeout fix: awslabs/aws-c-s3#461
- GetBodyPart API changes: awslabs/mountpoint-s3#1348
- Integration tests pass
--------

fix: consume mountpoint-s3-client 0.14.1

---

s3torchconnector/src/s3torchconnector/_user_agent.py
s3torchconnector/tst/e2e/dcp/test_e2e_s3_file_system.py
s3torchconnector/tst/e2e/test_e2e_s3_lightning_checkpoint.py
s3torchconnector/tst/unit/test_s3_client.py
s3torchconnector/tst/unit/test_user_agent.py

- Added Python version to user agent string to help track usage across Python versions
- Followed AWS SDK User Agent 2.0 formatting
- Updated unit tests and e2e tests (lightning and dcp)
Example: s3torchconnector/1.4.0 ua/2.0 lang/python#3.10.12 ...
Following RFC 9110 guidelines. 
No breaking changes - only updates existing user agent string format.
AWS SDK User Agent Header - User Agent 2.0
- Verified integration tests pass
--------

feat: add Python version to user agent string

---

.github/workflows/wheels.yml
run_cibuildwheel_on_ec2.sh
s3torchconnectorclient/pyproject.toml

Update build configuration for latest manylinux_2_28 images
The latest manylinux_2_28 images used for building wheels no longer support `devtoolset` and `llvm-toolset`. This PR updates our build configuration to use `gcc-toolset` and `clang` instead, ensuring compatibility with the most recent images.
Key changes:
- Replace `devtoolset` with `gcc-toolset-10`
- Replace `llvm-toolset` with the standard `clang` package
- Update environment variables and paths accordingly
- 
--------

Updates compilers settings to support manylinux_2_28 images

---

CHANGELOG.md
s3torchconnector/src/s3torchconnector/s3reader/s3reader.py
s3torchconnector/tst/unit/test_s3reader_common.py

- Add `seekable() `method returning True in S3Reader base class
- Add unit tests for `seekable` and `readable` methods
This allows us to eliminate PyTorch tensor copies during DCP loading.
- Our `S3Reader` extends `io.BufferedIOBase` (in [cpython/Lib/_pyio.py](https://github.com/python/cpython/blob/main/Lib/_pyio.py)) which defaults `seekable()` to False. 
- During DCP loading, PyTorch's [filesystem.py](https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/filesystem.py) checks [if the stream is seekable](https://github.com/pytorch/pytorch/blob/379ebdaf5e2fbf387de297f673254d005e583b31/torch/distributed/checkpoint/filesystem.py#L885), and if not, creates an extra `io.BytesIO` buffer copy for each tensor to allow `torch.load` to seek around it. 
- By implementing …

perf(s3reader): add seekable() method for DCP load optimization

---

CHANGELOG.md
s3torchconnector/src/s3torchconnector/s3writer.py
s3torchconnector/tst/unit/test_s3writer.py

S3Writer changes:
- Override closed property to reflect _closed flag instead of BufferedIOBase.__closed
- Update writable() to return False after S3Writer is closed
- When writing on closed streams, use python/cpython/Lib/_pyio.py _checkClosed() method to raise ValueError
These fixes improve correctness without changing normal behaviour.
Our [S3Writer](https://github.com/awslabs/s3-connector-for-pytorch/blob/main/s3torchconnector/src/s3torchconnector/s3writer.py) extends io.BufferedIOBase (in [_pyio.py](https://github.com/python/cpython/blob/main/Lib/_pyio.py)), which has a [closed](https://github.com/python/cpython/blob/055827528fa50c9a7707792f5fe264c4e20c07e9/Lib/_pyio.py#L462) property that reflects __closed, and we did not override it to represent our attribute self._closed. PyTorch …

fix(s3writer): override closed property and block writes after close

---

CHANGELOG.md
s3torchconnector/src/s3torchconnector/s3reader/sequential.py
s3torchconnector/tst/conftest.py
s3torchconnector/tst/unit/test_s3reader_common.py

This PR fixes a SequentialS3Reader edge case bug when seeking beyond EOF, with no impact on normal seek operations.
Changes:
- In SequentialS3Reader.seek(), clamp offset to _size before updating self/buffer positions
- Add test coverage for seek beyond EOF scenarios
This prevents SequentialS3Reader from seeking beyond EOF in SEEK_SET / SEEK_CUR modes, matching docstring behaviour "When seeking beyond the end of the file, always stay at EOF."
- Sequential reader incorrectly handles seek operations beyond object size: `_size` parameter is updated in `_prefetch_to_offset`, but `s3reader._position` and `s3reader._reader._buffer` positions are not clamped to object size.
- This is due to `BytesIO` object allowing seeks beyond its current size and the line `self._position = …

fix(s3reader): clamp sequential reader seek position to EOF
